# Generated by Django 5.2.8 on 2025-11-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_institution_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
