# Generated by Django 5.2.8 on 2025-11-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_attachment_feedback_attachment_graded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='max_points',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
